---

- name: Check and start a Windows service
  hosts: win

  tasks:
    - name: Set service startup mode to auto and ensure it is started
      win_service:
        name: wuauserv
        start_mode: auto
        state: started

- name: windows rolling update
  hosts: win
  tasks:
    - name: Install all critical and security updates
      ansible.windows.win_updates:
         category_names:
           - CriticalUpdates
           - SecurityUpdates
           - DefinitionUpdates   
         state: installed
         reboot: false
         skip_optional: true
         log_path: C:\Temp\windowsupdate.txt
